### ISSUE TITLE
Sales Event Report Broken

### ISSUE THREAD

**Issue by Dassy23** [beardon/apple-reporter#13]
This error appears when trying to download event report. 
` "Sales and Trends Reporter is currently available."
FetchError: invalid response body at: https://reportingitc-reporter.apple.com/reportservice/sales/v1 reason: incorrect header check
    at Gunzip.<anonymous> (/Users/cmg/projects/gcp_vendor_apple/reporter/node_modules/node-fetch/lib/body.js:123:11)
    at Gunzip.emit (events.js:208:15)
    at Zlib.zlibOnError [as onerror] (zlib.js:171:8) {
  name: 'FetchError',
  message: 'invalid response body at: https://reportingitc-reporter.apple.com/reportservice/sales/v1 reason: incorrect header check',
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR'
} `
I believe this is due to the file format changes from apple, 
https://itunespartner.apple.com/en/music/news/100002692
Btw thanks for the great work with this lib!

**Comment by keybrdist** [comment]
I am seeing this error. Any solution for it?

**Comment by ghyath5** [comment]
any updates here ?
